### ISSUE TITLE
Features to add

### ISSUE THREAD

**Issue by Legitloler** [Fruity-Grebbles/Caves-and-Cheese#1]
Add a level detail near the name
Add a roll for strength -->Since we sometimes need this
Add a armor tab --> This should just add to our defense 
Add a notes tab where we can right stuff that we know from the game
Add a skill tab--> Just a list for reference

**Comment by grebz-dev** [comment]
* Level detail has been added
* Roll for strength is under consideration
* Working on a design for an armor tab; Please suggest limitations on what armor can be equipped. What happens to armor when it's not equipped? Can you carry armor that you're not using?
* Skill and notes tabs should be easy enough to implement; Expect them in 0.3

**Comment by grebz-dev** [comment]
Previous update incorporates requested features.
